### ISSUE TITLE
job_class.coffee:37:9 - Exception in setTimeout callback: Error: splitLongArray: bad params

### ISSUE THREAD

**Issue by a4xrbj1** [vsivsi/meteor-job-collection#265]
It seems the update to the newest Meteor patch 1.6.0.1 is causing this error as it hasn't happened to me with version 1.6

The error shows on startup of the server side code only:

```
Exception in setTimeout callback: Error: splitLongArray: bad params
I20171226-01:07:49.639(8)?     at splitLongArray (packages/vsivsi_job-collection/job/src/job_class.coffee:37:9)
I20171226-01:07:49.639(8)?     at Function.Job.restartJobs (packages/vsivsi_job-collection/job/src/job_class.coffee:537:19)
I20171226-01:07:49.640(8)?     at JobCollectionBase.restartJobs (packages/vsivsi_job-collection/src/shared.coffee:169:31)
I20171226-01:07:49.640(8)?     at usersGetServices (server/jobUpdatesWorker.js:110:20)
I20171226-01:07:49.640(8)?     at JobQueue.worker (server/jobUpdatesWorker.js:168:5)
I20171226-01:07:49.640(8)?     at JobQueue._process (packages/vsivsi_job-collection/job/src/job_class.coffee:215:8)
I20171226-01:07:49.640(8)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
I20171226-01:07:49.641(8)?     at packages/meteor.js:502:25
I20171226-01:07:49.641(8)?     at runWithEnvironment (packages/meteor.js:1240:24)
```

**Comment by a4xrbj1** [comment]
Can be closed, this is due to our code trying to restart a `canceled` job
